/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.1/samples
 */


plugins {
    application 
}

repositories {
    mavenCentral() 
}

dependencies {
    implementation("com.github.javaparser:javaparser-core:3.25.10") 
    
    // https://mvnrepository.com/artifact/com.opencsv/opencsv
    implementation("com.opencsv:opencsv:5.9")
}

application {
    mainClass.set("JavaASTExtract") 
}

sourceSets {
    main {
        java {
            srcDir(".") 
        }
    }
}