name: CI/CD Pipeline

on:
  push:
    branches:
      - cicd_test
    paths-ignore:
      - '**.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code you you you you you
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image for service_ai_analysis
    - name: Build and Push Docker image for service_ai_analysis
      uses: docker/build-push-action@v2
      with:
        context:./services/service_ai_analysis
        file:./services/service_ai_analysis/Dockerfile
        push: true
        tags: youssefroulamellah/service_ai_analysis:latest

    # Run the built Docker image as a container
    - name: Run Docker container
      container:
        image: youssefroulamellah/service_ai_analysis:latest
        command: "your_command_here"