name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code - Heyyy yaa
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push Docker image for service_ai_analysis
    - name: Build and Push Docker image for service_ai_analysis
      uses: docker/build-push-action@v2
      with:
        context: ./services
        file: ./services/service_ai_analysis/Dockerfile
        push: true
        tags: yroulamellah/log-density-tool:latest_ai_analysis

    # Run the built Docker image tests
    - name: Run Tests for service_ai_analysis in Docker container
      run: |
        docker run yroulamellah/log-density-tool:latest_ai_analysis pytest

    # Build and push Docker image for service_model_creation
    - name: Build and Push Docker image for service_model_creation
      uses: docker/build-push-action@v2
      with:
        context: ./services
        file: ./services/service_model_creation/Dockerfile
        push: true
        tags: yroulamellah/log-density-tool:latest_model_creation

    # Run the built Docker image tests
    - name: Run Tests for service_model_creation in Docker container
      run: |
        docker run yroulamellah/log-density-tool:latest_model_creation pytest