name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

   
    - name: Build and Push Docker image for service_ai_analysis
      uses: docker/build-push-action@v2
      with:
        context: ./services/service_ai_analysis
        file: ./services/service_ai_analysis/Dockerfile
        push: true
        tags: youssefroulamellah/service_ai_analysis:latest


    - name: Build and Push Docker image for service_model_creation
      uses: docker/build-push-action@v2
      with:
        context: ./services/service_model_creation
        file: ./services/service_model_creation/Dockerfile
        push: true
        tags: youssefroulamellah/service_model_creation:latest


    - name: Run tests for service_ai_analysis
      run: |
        cd services/service_ai_analysis
        poetry install
        poetry run pytest


    - name: Run tests for service_model_creation
      run: |
        cd services/service_model_creation
        poetry install
        poetry run pytest
