@startuml

title Diagramme de classes

legend right
    |Couleur| État |
    |<#DDDDDD>| Implémenté|
    |<#FFFF00>| Pas encore implémenté|
endlegend

package services {
    class extension {
        +activate()
    }
}

package backend {
    class main {
        +app: FastAPI
    }

    package controllers {
        class model_controller {
            +create_model_req(project: JavaProject)
        }

        class analysis_controller #FFFF00 {
            +tbd(project: JavaProject)
        }
    }

    package services {
        class model_service {
            +create_model(project_url: str)
        }
    }

    package models {
        class java_project {
            +url: str
            +name: str
            +check_url(cls, value): str
        }
    }

    package training {
        class LSTM_Log_Density_Model
        class clustering
    }
}


extension --> main

main --> model_controller
main --> analysis_controller

model_controller --> java_project
analysis_controller --> java_project

model_controller --> model_service

model_service --> LSTM_Log_Density_Model
LSTM_Log_Density_Model -l-> clustering

@enduml