@startuml

title Diagramme de classes

package PlugIn {
    class "PlugInClass?" as tbd {
        +repo_url: str
        +repo_name: str
        +create_model()
        +analyze_file()
        +analyze_method()
    }
}

package "FastAPI App" {
    class MainApp {
        +app: FastAPI
        +run()
    }

    package Controllers {
        class training_model_controller {
            +create_model(repo_url: str)
        }

        class AnalysisController {
            +analyze_file(repo_name: str, filename: str)
            +analyze_method(repo_name: str, filename: str, method: str)
        }

        class ProjectURL {
            +url: str
            +name: str
        }
    }

    package services {
        class training_model_service {
            +create_model_service()
        }

        class run_model
        class model_loader {
            +find_model(repo_name: str)
        }
    }
}

tbd --> MainApp

MainApp --> training_model_controller
MainApp --> AnalysisController

training_model_controller --> training_model_service
training_model_controller -> ProjectURL
AnalysisController --> run_model
AnalysisController --> model_loader

@enduml