@startuml

title Diagramme de composants - Dev

actor "Équipe de développement" as team

node "Machine d'un développeur" as machine {
    node "VS Code" as IDE {
        package "Projet Java" as project {
            file "Fichiers .java" as files
        }

        component "Plugin" as plugin
    }
}

cloud "Serveur\nLocalhost" as server {
    file "Modèle AI" as model
}

node "Générateur de modèles" as generator

team -u-> plugin: "Demande une analyse du\nd'un fichier Java"
team -u-> project: "Effectue des modifications"
team .l.> generator: "Fait analyser son projet Java pour créer un\nmodèle AI en envoyant l'URL du repo GitHub"
generator -u-> model: "Crée un modèle AI"
plugin -l-> model: "Envoie le contenu du fichier Java à analyser"
model -r-> plugin: "Pourcentage de densité de log d'un fichier Java"

@enduml