@startuml

title Diagramme de composants - Dev 2

actor "Équipe de développement" as team

node "Machine d'un développeur" as machine {
    node "VS Code" as IDE {
        package "Projet Java" as project {
            file "Fichiers .java" as files
        }

        component "Plugin" as plugin
    }
}

cloud "Serveur\nLocalhost" as server {
    file "Modèle AI" as model
}

node "Générateur de modèles" as generator

team -u-> plugin: "Demande la création d'un modèle AI en\nenvoyant l'URL GitHub du projet Java\n\nDemande une analyse du d'un fichier Java"
team -u-> project: "Effectue des modifications"
plugin -d-> generator: "Envoie le projet Java analysé"
generator -u-> model: "Crée un modèle AI"
model -r-> plugin: "Pourcentage de densité de log d'un fichier Java"
plugin -l-> model: "Envoie le contenu du fichier Java à analyser"

@enduml