@startuml

title Diagramme de composants - Prod

actor "Équipe de développement" as team

node "Machine d'un développeur" as machine {
    node "VS Code" as IDE {
        package "Projet Java" as project {
            file "Fichiers .java" as files
        }

        component "Plugin" as plugin
    }
}

cloud "Serveur\nLocalhost" as server {
    node "Service d'analyse" as serviceA {
        file "Modèle AI" as model
    }

    node "Service générateur de modèles" as serviceB
}

team -u-> plugin: "Demande la création d'un modèle AI en\nenvoyant l'URL GitHub du projet Java\n\nDemande une analyse du d'un fichier Java"
team -u-> project: "Effectue des modifications"
plugin -d-> serviceB: "Envoie le projet Java analysé"
serviceB -u-> serviceA: "Crée un modèle AI"
serviceA -r-> plugin: "Pourcentage de densité de log d'un fichier Java"
plugin -l-> serviceA: "Envoie le contenu du fichier Java à analyser"

@enduml