@startuml
title DS - CU03 Analyser une méthode Java - TBD
skinparam style strictuml

participant ":extension" as extension
participant ":main" as main
participant ":analysis_controller" as analysisController
participant ":ModelLoader?" as modelLoader
participant ":run_model?" as run_model

-> plugin : POST analyze_method(repo_name, filename, method)

plugin -> main : analyze_method(repo_name, filename, method)
main -> analysis_controller : analyze_method(repo_name, filename, method)

analysis_controller -> modelLoader : load_model(repo_name)
modelLoader --> analysis_controller : Path du modèle

analysis_controller -> run_model

run_model --> analysis_controller : Pourcentage et catégorie\nde densité de log
analysis_controller --> main : Pourcentage et catégorie\nde densité de log
main --> plugin : Pourcentage et catégorie\nde densité de log
<-- plugin : Pourcentage et catégorie\nde densité de log
@enduml