@startuml
title DS - CU01 Créer un modèle AI
skinparam style strictuml

participant ":extension" as extension
participant ":main" as main
participant ":model_controller" as model_controller
participant JavaProject
participant ":model_service" as model_service
participant ":git.Repo" as github

-> extension : URL du dépôt de code GitHub

extension -> main : POST /model/create(JSON body {url})
main -> model_controller : create_model_req(JavaProject.url)
model_controller -> JavaProject : check_url(JavaProject, value = JavaProject.url)
alt JavaProject.url est vide
    JavaProject --> model_controller : Status code 422: The URL to the\nGitHub repository must not be empty.
else
    JavaProject --> model_controller : JavaProject.url
    model_controller -> model_service : create_model(ProjectUrl.url)

    alt Projet n'existe pas localement
        model_service -> github : Repo.clone_from(url, project_path)
        model_service --> model_controller : Message de confirmation de création de modèle
    else
        model_service --> model_controller : Message indiquant que le dépôt de code existe déjà
    end
end

<-- model_controller : Résultat
@enduml