@startuml
title DS - CU02 Analyser un fichier Java
skinparam style strictuml

participant ":PlugInClass?" as plugin
participant ":MainApp" as main
participant ":AnalysisController" as analysisController
participant ":ModelLoader" as modelLoader
participant ":run_model" as run_model

-> plugin : POST analyze_file(repo_name, filename)

plugin -> main : analyze_file(repo_name, filename)
main -> analysisController : analyze_file(repo_name, filename)

analysisController -> modelLoader : load_model(repo_name)
modelLoader --> analysisController : Path du modèle

analysisController -> run_model

run_model --> analysisController : Pourcentage et catégorie\nde densité de log
analysisController --> main : Pourcentage et catégorie\nde densité de log
main --> plugin : Pourcentage et catégorie\nde densité de log
<-- plugin : Pourcentage et catégorie\nde densité de log
@enduml