@startuml
title DS - CU02 Analyser un fichier Java - TBD
skinparam style strictuml

participant ":extension" as extension
participant ":main" as main
participant ":analysis_controller" as analysis_controller
participant ":ModelLoader?" as modelLoader
participant ":run_model?" as run_model

-> extension : POST analyze_file(repo_name, filename)

extension -> main : analyze_file(repo_name, filename)
main -> analysis_controller : analyze_file(repo_name, filename)

analysis_controller -> modelLoader : load_model(repo_name)
modelLoader --> analysis_controller : Path du modèle

analysis_controller -> run_model

run_model --> analysis_controller : Pourcentage et catégorie\nde densité de log
analysis_controller --> main : Pourcentage et catégorie\nde densité de log
main --> extension : Pourcentage et catégorie\nde densité de log
<-- extension : Pourcentage et catégorie\nde densité de log
@enduml