@startuml
title Vue architecturale de type allocation - Performance

node "Machine de l'utilisateur" as machine {
    node "VS Code" as IDE {
        package "Projet Java" {
            file Code
        }

        component "plugin\nComposant 1" as plugin
    }
}

cloud "Serveur\nLocalhost\nComposant 2" as server {
    file "Modèle AI" as model
}

node "Black Box PFE_Server\nComposant 3" as black_box {
}

actor "Équipe PFE 019" as team

plugin ..> server: "requête\nGET ou POST"
model -[dotted]-> IDE: "Pourcentage de densité\nde log suggéré"
black_box -u-> model: "Crée un modèle AI"
team .r.> black_box: "Demande au Black Box de\ncréer un nouveau modèle AI"

@enduml